### ISSUE TITLE
History lost when creating Category

### ISSUE THREAD

**Issue by OskarKlintrot** [Certaincy/Intranet#165]
## Description
When navigating to Category and creating a new Category the history about where the user is coming from is lost.

## Acceptance Criterias

- [x] Possible to navigate from Faqs/Policies to Category, create new category and navigate back via links at the bottom of the page

**Comment by ps222nq** [comment]
Issue resolved, pending review and tests in pull request #166
Can navigate from either FAQ or Policies and back without problems
