### ISSUE TITLE
Authentication with AD

### ISSUE THREAD

**Issue by OskarKlintrot** [Certaincy/Intranet#2]
## Description
`AuthenticationService.cs` connected to our AD. See [this blog post](https://nicolas.guelpa.me/blog/2017/02/15/dotnet-core-ldap-authentication.html) for example implementation.

## Acceptance Criteras
* [x] Unit Tests
* [x] DI
* [ ] Dummy for local dev?
* [x] Connection to LDAP

**Comment by calleleppajoki** [comment]
Idea: ENV variable to select if we're using AD or local dummy.
